server:
  error:
    whitelabel:
      enabled: false
# spring pro
spring:
  # jpa properties
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database: h2
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  # banner properties
  main:
    banner-mode: off